(function (namespace, $, undefined) {

  //Private Property
  var markerCatalog = [
  { "iconID": 0, "width": 66, "height": 44, "originX": 0, "originY": 0, "anchorX": 0, "anchorY": 44, "markerImgUrl": "images/AssetMapMarkers/Generic/FlagYellow_noncat_MapMarker.png",
  	"iconImageFolder": "images/AssetIcons", "iconFileName": "FlagYellow_non-cat.png", "OEMIconFileName": "null" },
  { "iconID": 1, "width": 74, "height": 44, "originX": 0, "originY": 0, "anchorX": 0, "anchorY": 44, "markerImgUrl": "images/AssetMapMarkers/CAT/ArticulatedTruck_MapMarker.png",
  	"iconImageFolder": "images/AssetIcons", "iconFileName": "ArticulatedTruck.png", "OEMIconFileName": "CATHeaderLogo_SM.png" },
  { "iconID": 2, "width": 66, "height": 44, "originX": 0, "originY": 0, "anchorX": 0, "anchorY": 44, "markerImgUrl": "images/AssetMapMarkers/CAT/BackhoeLoader_MapMarker.png",
  	"iconImageFolder": "images/AssetIcons", "iconFileName": "BackhoeLoader.png", "OEMIconFileName": "CATHeaderLogo_SM.png" },
  { "iconID": 3, "width": 74, "height": 44, "originX": 0, "originY": 0, "anchorX": 0, "anchorY": 44, "markerImgUrl": "images/AssetMapMarkers/CAT/ColdPlaner_MapMarker.png",
  	"iconImageFolder": "images/AssetIcons", "iconFileName": "ColdPlaner.png", "OEMIconFileName": "CATHeaderLogo_SM.png" },
  { "iconID": 4, "width": 66, "height": 44, "originX": 0, "originY": 0, "anchorX": 0, "anchorY": 44, "markerImgUrl": "images/AssetMapMarkers/CAT/MultiTerrainLoader_MapMarker.png",
  	"iconImageFolder": "images/AssetIcons", "iconFileName": "MultiTerrainLoader.png", "OEMIconFileName": "CATHeaderLogo_SM.png" },
  { "iconID": 5, "width": 66, "height": 44, "originX": 0, "originY": 0, "anchorX": 0, "anchorY": 44, "markerImgUrl": "images/AssetMapMarkers/CAT/Compactor_MapMarker.png",
  	"iconImageFolder": "images/AssetIcons", "iconFileName": "Compactor.png", "OEMIconFileName": "CATHeaderLogo_SM.png" },
  { "iconID": 6, "width": 74, "height": 44, "originX": 0, "originY": 0, "anchorX": 0, "anchorY": 44, "markerImgUrl": "images/AssetMapMarkers/CAT/FellerBuncher_MapMarker.png",
  	"iconImageFolder": "images/AssetIcons", "iconFileName": "FellerBuncher.png", "OEMIconFileName": "CATHeaderLogo_SM.png"},
  { "iconID": 7, "width": 74, "height": 44, "originX": 0, "originY": 0, "anchorX": 0, "anchorY": 44, "markerImgUrl": "images/AssetMapMarkers/CAT/ForestMachine_MapMarker.png",
  	"iconImageFolder": "images/AssetIcons", "iconFileName": "ForestMachine.png", "OEMIconFileName": "CATHeaderLogo_SM.png"},
  { "iconID": 8, "width": 74, "height": 44, "originX": 0, "originY": 0, "anchorX": 0, "anchorY": 44, "markerImgUrl": "images/AssetMapMarkers/CAT/Forwarder_MapMarker.png",
  	"iconImageFolder": "images/AssetIcons", "iconFileName": "Forwarder.png", "OEMIconFileName": "CATHeaderLogo_SM.png"},
  { "iconID": 9, "width": 74, "height": 44, "originX": 0, "originY": 0, "anchorX": 0, "anchorY": 44, "markerImgUrl": "images/AssetMapMarkers/CAT/Harvester_MapMarker.png",
  	"iconImageFolder": "images/AssetIcons", "iconFileName": "Harvester.png", "OEMIconFileName": "CATHeaderLogo_SM.png"},
  { "iconID": 10, "width": 74, "height": 44, "originX": 0, "originY": 0, "anchorX": 0, "anchorY": 44, "markerImgUrl": "images/AssetMapMarkers/CAT/HydraulicExcavator_MapMarker.png",
  	"iconImageFolder": "images/AssetIcons", "iconFileName": "HydraulicExcavator.png", "OEMIconFileName": "CATHeaderLogo_SM.png"},
  { "iconID": 11, "width": 70, "height": 44, "originX": 0, "originY": 0, "anchorX": 0, "anchorY": 44, "markerImgUrl": "images/AssetMapMarkers/CAT/IndustrialLoader_MapMarker.png",
  	"iconImageFolder": "images/AssetIcons", "iconFileName": "IndustrialLoader.png", "OEMIconFileName": "CATHeaderLogo_SM.png"},
  { "iconID": 12, "width": 74, "height": 44, "originX": 0, "originY": 0, "anchorX": 0, "anchorY": 44, "markerImgUrl": "images/AssetMapMarkers/CAT/KnuckboomLoader_MapMarker.png",
  	"iconImageFolder": "images/AssetIcons", "iconFileName": "KnuckleboomLoader.png", "OEMIconFileName": "CATHeaderLogo_SM.png"},
  { "iconID": 13, "width": 74, "height": 44, "originX": 0, "originY": 0, "anchorX": 0, "anchorY": 44, "markerImgUrl": "images/AssetMapMarkers/CAT/MaterialHandler_MapMarker.png",
  	"iconImageFolder": "images/AssetIcons", "iconFileName": "MaterialHandler.png", "OEMIconFileName": "CATHeaderLogo_SM.png"},
  { "iconID": 14, "width": 74, "height": 44, "originX": 0, "originY": 0, "anchorX": 0, "anchorY": 44, "markerImgUrl": "images/AssetMapMarkers/CAT/MotorGrader_MapMarker.png",
  	"iconImageFolder": "images/AssetIcons", "iconFileName": "MotorGrader.png", "OEMIconFileName": "CATHeaderLogo_SM.png"},
  { "iconID": 15, "width": 70, "height": 44, "originX": 0, "originY": 0, "anchorX": 0, "anchorY": 44, "markerImgUrl": "images/AssetMapMarkers/CAT/OffHighwayTruck_MapMarker.png",
  	"iconImageFolder": "images/AssetIcons", "iconFileName": "OffHighwayTruck.png", "OEMIconFileName": "CATHeaderLogo_SM.png"},
  { "iconID": 16, "width": 70, "height": 44, "originX": 0, "originY": 0, "anchorX": 0, "anchorY": 44, "markerImgUrl": "images/AssetMapMarkers/CAT/PavingEquipment_MapMarker.png",
  	"iconImageFolder": "images/AssetIcons", "iconFileName": "PavingEquipment.png", "OEMIconFileName": "CATHeaderLogo_SM.png"},
  { "iconID": 17, "width": 74, "height": 44, "originX": 0, "originY": 0, "anchorX": 0, "anchorY": 44, "markerImgUrl": "images/AssetMapMarkers/CAT/PipeLayer_MapMarker.png",
  	"iconImageFolder": "images/AssetIcons", "iconFileName": "Pipelayer.png", "OEMIconFileName": "CATHeaderLogo_SM.png"},
  { "iconID": 18, "width": 70, "height": 44, "originX": 0, "originY": 0, "anchorX": 0, "anchorY": 44, "markerImgUrl": "images/AssetMapMarkers/CAT/RoadReclaimer_MapMarker.png",
  	"iconImageFolder": "images/AssetIcons", "iconFileName": "RoadReclaimer.png", "OEMIconFileName": "CATHeaderLogo_SM.png"},
  { "iconID": 19, "width": 66, "height": 44, "originX": 0, "originY": 0, "anchorX": 0, "anchorY": 44, "markerImgUrl": "images/AssetMapMarkers/CAT/SkidSteerLoader_MapMarker.png",
  	"iconImageFolder": "images/AssetIcons", "iconFileName": "SkidSteerLoader.png", "OEMIconFileName": "CATHeaderLogo_SM.png"},
  { "iconID": 20, "width": 70, "height": 44, "originX": 0, "originY": 0, "anchorX": 0, "anchorY": 44, "markerImgUrl": "images/AssetMapMarkers/CAT/Skidder_MapMarker.png",
  	"iconImageFolder": "images/AssetIcons", "iconFileName": "Skidder.png", "OEMIconFileName": "CATHeaderLogo_SM.png"},
  { "iconID": 21, "width": 74, "height": 44, "originX": 0, "originY": 0, "anchorX": 0, "anchorY": 44, "markerImgUrl": "images/AssetMapMarkers/CAT/Telehandler_MapMarker.png",
  	"iconImageFolder": "images/AssetIcons", "iconFileName": "Telehandler.png", "OEMIconFileName": "CATHeaderLogo_SM.png"},
  { "iconID": 22, "width": 70, "height": 44, "originX": 0, "originY": 0, "anchorX": 0, "anchorY": 44, "markerImgUrl": "images/AssetMapMarkers/CAT/TrackLoader_MapMarker.png",
  	"iconImageFolder": "images/AssetIcons", "iconFileName": "TrackLoader.png", "OEMIconFileName": "CATHeaderLogo_SM.png"},
  { "iconID": 23, "width": 74, "height": 44, "originX": 0, "originY": 0, "anchorX": 0, "anchorY": 44, "markerImgUrl": "images/AssetMapMarkers/CAT/TrackTypeTractor_MapMarker.png",
  	"iconImageFolder": "images/AssetIcons", "iconFileName": "TrackTypeTractor.png", "OEMIconFileName": "CATHeaderLogo_SM.png"},
  { "iconID": 24, "width": 74, "height": 44, "originX": 0, "originY": 0, "anchorX": 0, "anchorY": 44, "markerImgUrl": "images/AssetMapMarkers/CAT/UndergroundMining_MapMarker.png",
  	"iconImageFolder": "images/AssetIcons", "iconFileName": "UndergroundMining.png", "OEMIconFileName": "CATHeaderLogo_SM.png"},
  { "iconID": 25, "width": 70, "height": 44, "originX": 0, "originY": 0, "anchorX": 0, "anchorY": 44, "markerImgUrl": "images/AssetMapMarkers/CAT/WheelDozer_MapMarker.png",
  	"iconImageFolder": "images/AssetIcons", "iconFileName": "WheelDozer.png", "OEMIconFileName": "CATHeaderLogo_SM.png"},
  { "iconID": 26, "width": 74, "height": 44, "originX": 0, "originY": 0, "anchorX": 0, "anchorY": 44, "markerImgUrl": "images/AssetMapMarkers/CAT/WheelExcavator_MapMarker.png",
  	"iconImageFolder": "images/AssetIcons", "iconFileName": "WheelExcavator.png", "OEMIconFileName": "CATHeaderLogo_SM.png"},
  { "iconID": 27, "width": 70, "height": 44, "originX": 0, "originY": 0, "anchorX": 0, "anchorY": 44, "markerImgUrl": "images/AssetMapMarkers/CAT/WheelLoader_MapMarker.png",
  	"iconImageFolder": "images/AssetIcons", "iconFileName": "WheelLoader.png", "OEMIconFileName": "CATHeaderLogo_SM.png"},
  { "iconID": 28, "width": 74, "height": 44, "originX": 0, "originY": 0, "anchorX": 0, "anchorY": 44, "markerImgUrl": "images/AssetMapMarkers/CAT/WheelTractorScraper_MapMarker.png",
  	"iconImageFolder": "images/AssetIcons", "iconFileName": "WheelTractorScraper.png", "OEMIconFileName": "CATHeaderLogo_SM.png"},
  { "iconID": 29, "width": 74, "height": 44, "originX": 0, "originY": 0, "anchorX": 0, "anchorY": 44, "markerImgUrl": "images/AssetMapMarkers/CAT/WheelTractorScrapers_MapMarker.png",
  	"iconImageFolder": "images/AssetIcons", "iconFileName": "WheelTractorScrapers.png", "OEMIconFileName": "CATHeaderLogo_SM.png"},
  { "iconID": 30, "width": 66, "height": 44, "originX": 0, "originY": 0, "anchorX": 0, "anchorY": 44, "markerImgUrl": "images/AssetMapMarkers/Generic/FlagYellow_noncat_MapMarker.png",
  	"iconImageFolder": "images/AssetIcons", "iconFileName": "FlagYellow_non-cat.png", "OEMIconFileName": "NoLogo.png"},
  { "iconID": 31, "width": 70, "height": 44, "originX": 0, "originY": 0, "anchorX": 0, "anchorY": 44, "markerImgUrl": "images/AssetMapMarkers/Generic/ArticulatedTruck_noncat_MapMarker.png",
  	"iconImageFolder": "images/AssetIcons", "iconFileName": "ArticulatedTruck_lrg_non-cat.png", "OEMIconFileName": "NoLogo.png"},
  { "iconID": 32, "width": 70, "height": 44, "originX": 0, "originY": 0, "anchorX": 0, "anchorY": 44, "markerImgUrl": "images/AssetMapMarkers/Generic/BackhoeLoader_noncat_MapMarker.png",
  	"iconImageFolder": "images/AssetIcons", "iconFileName": "BackhoeLoader_non-cat.png", "OEMIconFileName": "NoLogo.png"},
  { "iconID": 33, "width": 74, "height": 44, "originX": 0, "originY": 0, "anchorX": 0, "anchorY": 44, "markerImgUrl": "images/AssetMapMarkers/Generic/MillingMachine_noncat_MapMarker.png",
  	"iconImageFolder": "images/AssetIcons", "iconFileName": "MillingMachine_non-cat.png", "OEMIconFileName": "NoLogo.png"},
  { "iconID": 34, "width": 66, "height": 44, "originX": 0, "originY": 0, "anchorX": 0, "anchorY": 44, "markerImgUrl": "images/AssetMapMarkers/Generic/Compactor_noncat_MapMarker.png",
  	"iconImageFolder": "images/AssetIcons", "iconFileName": "Compactor_non-cat.png", "OEMIconFileName": "NoLogo.png"},
  { "iconID": 35, "width": 70, "height": 44, "originX": 0, "originY": 0, "anchorX": 0, "anchorY": 44, "markerImgUrl": "images/AssetMapMarkers/Generic/FellerBuncher_noncat_MapMarker.png",
  	"iconImageFolder": "images/AssetIcons", "iconFileName": "FellerBuncher_non-cat.png", "OEMIconFileName": "NoLogo.png"},
  { "iconID": 36, "width": 74, "height": 44, "originX": 0, "originY": 0, "anchorX": 0, "anchorY": 44, "markerImgUrl": "images/AssetMapMarkers/Generic/FlatbedTruck_noncat_MapMarker.png",
  	"iconImageFolder": "images/AssetIcons", "iconFileName": "FlatbedTruck_non-cat.png", "OEMIconFileName": "NoLogo.png"},
  { "iconID": 37, "width": 70, "height": 44, "originX": 0, "originY": 0, "anchorX": 0, "anchorY": 44, "markerImgUrl": "images/AssetMapMarkers/Generic/ForestMachine_noncat_MapMarker.png",
  	"iconImageFolder": "images/AssetIcons", "iconFileName": "ForestMachine_non-cat.png", "OEMIconFileName": "NoLogo.png"},
  { "iconID": 38, "width": 74, "height": 44, "originX": 0, "originY": 0, "anchorX": 0, "anchorY": 44, "markerImgUrl": "images/AssetMapMarkers/Generic/Forwarder_noncat_MapMarker.png",
  	"iconImageFolder": "images/AssetIcons", "iconFileName": "Forwarder_non-cat.png", "OEMIconFileName": "NoLogo.png"},
  { "iconID": 39, "width": 74, "height": 44, "originX": 0, "originY": 0, "anchorX": 0, "anchorY": 44, "markerImgUrl": "images/AssetMapMarkers/Generic/TankerTruck_noncat_MapMarker.png",
  	"iconImageFolder": "images/AssetIcons", "iconFileName": "TankerTruck_non-cat.png", "OEMIconFileName": "CATHeaderLogo_SM.png"},
  { "iconID": 40, "width": 70, "height": 44, "originX": 0, "originY": 0, "anchorX": 0, "anchorY": 44, "markerImgUrl": "images/AssetMapMarkers/Generic/Harvester_noncat_MapMarker.png",
  	"iconImageFolder": "images/AssetIcons", "iconFileName": "Harvester_non-cat.png", "OEMIconFileName": "CATHeaderLogo_SM.png"},
  { "iconID": 41, "width": 70, "height": 44, "originX": 0, "originY": 0, "anchorX": 0, "anchorY": 44, "markerImgUrl": "images/AssetMapMarkers/Generic/HaulTruck_noncat_MapMarker.png",
  	"iconImageFolder": "images/AssetIcons", "iconFileName": "HaulTruck_non-cat.png", "OEMIconFileName": "CATHeaderLogo_SM.png"},
  { "iconID": 42, "width": 70, "height": 44, "originX": 0, "originY": 0, "anchorX": 0, "anchorY": 44, "markerImgUrl": "images/AssetMapMarkers/Generic/HydraulicExcavator_noncat_MapMarker.png",
  	"iconImageFolder": "images/AssetIcons", "iconFileName": "HydraulicExcavator_non-cat.png", "OEMIconFileName": "CATHeaderLogo_SM.png"},
  { "iconID": 43, "width": 70, "height": 44, "originX": 0, "originY": 0, "anchorX": 0, "anchorY": 44, "markerImgUrl": "images/AssetMapMarkers/Generic/IndustrialLoader_noncat_MapMarker.png",
  	"iconImageFolder": "images/AssetIcons", "iconFileName": "IndustrialLoader_non-cat.png", "OEMIconFileName": "CATHeaderLogo_SM.png"},
  { "iconID": 44, "width": 70, "height": 44, "originX": 0, "originY": 0, "anchorX": 0, "anchorY": 44, "markerImgUrl": "images/AssetMapMarkers/Generic/KnuckboomLoader_noncat_MapMarker.png",
  	"iconImageFolder": "images/AssetIcons", "iconFileName": "KnuckleboomLoader_non-cat.png", "OEMIconFileName": "CATHeaderLogo_SM.png"},
  { "iconID": 45, "width": 66, "height": 44, "originX": 0, "originY": 0, "anchorX": 0, "anchorY": 44, "markerImgUrl": "images/AssetMapMarkers/Generic/MaterialHandler_noncat_MapMarker.png",
  	"iconImageFolder": "images/AssetIcons", "iconFileName": "MaterialHandler_non-cat.png", "OEMIconFileName": "CATHeaderLogo_SM.png"},
  { "iconID": 46, "width": 74, "height": 44, "originX": 0, "originY": 0, "anchorX": 0, "anchorY": 44, "markerImgUrl": "images/AssetMapMarkers/Generic/MotorGrader_noncat_MapMarker.png",
  	"iconImageFolder": "images/AssetIcons", "iconFileName": "MotorGrader_non-cat.png", "OEMIconFileName": "CATHeaderLogo_SM.png"},
  { "iconID": 47, "width": 66, "height": 44, "originX": 0, "originY": 0, "anchorX": 0, "anchorY": 44, "markerImgUrl": "images/AssetMapMarkers/Generic/MultiTerrainLoader_noncat_MapMarker.png",
  	"iconImageFolder": "images/AssetIcons", "iconFileName": "MultiTerrainLoader_non-cat.png", "OEMIconFileName": "CATHeaderLogo_SM.png"},
  { "iconID": 48, "width": 70, "height": 44, "originX": 0, "originY": 0, "anchorX": 0, "anchorY": 44, "markerImgUrl": "images/AssetMapMarkers/Generic/OffHighwayTruck_noncat_MapMarker.png",
  	"iconImageFolder": "images/AssetIcons", "iconFileName": "OffHighwayTruck_non-cat.png", "OEMIconFileName": "CATHeaderLogo_SM.png"},
  { "iconID": 49, "width": 66, "height": 44, "originX": 0, "originY": 0, "anchorX": 0, "anchorY": 44, "markerImgUrl": "images/AssetMapMarkers/Generic/DualDrumAsphaltRoller_noncat_MapMarker.png",
  	"iconImageFolder": "images/AssetIcons", "iconFileName": "DualDrumAsphaltRoller_non-cat.png", "OEMIconFileName": "CATHeaderLogo_SM.png"},
  { "iconID": 50, "width": 70, "height": 44, "originX": 0, "originY": 0, "anchorX": 0, "anchorY": 44, "markerImgUrl": "images/AssetMapMarkers/Generic/PipeLayer_noncat_MapMarker.png",
  	"iconImageFolder": "images/AssetIcons", "iconFileName": "Pipelayer_non-cat.png", "OEMIconFileName": "CATHeaderLogo_SM.png"},
  { "iconID": 51, "width": 74, "height": 44, "originX": 0, "originY": 0, "anchorX": 0, "anchorY": 44, "markerImgUrl": "images/AssetMapMarkers/Generic/RoadReclaimer_noncat_MapMarker.png",
  	"iconImageFolder": "images/AssetIcons", "iconFileName": "RoadReclaimer_non-cat.png", "OEMIconFileName": "CATHeaderLogo_SM.png"},
  { "iconID": 52, "width": 70, "height": 44, "originX": 0, "originY": 0, "anchorX": 0, "anchorY": 44, "markerImgUrl": "images/AssetMapMarkers/Generic/ServiceTruck_noncat_MapMarker.png",
  	"iconImageFolder": "images/AssetIcons", "iconFileName": "ServiceTruck_non-cat.png", "OEMIconFileName": "CATHeaderLogo_SM.png"},
  { "iconID": 53, "width": 66, "height": 44, "originX": 0, "originY": 0, "anchorX": 0, "anchorY": 44, "markerImgUrl": "images/AssetMapMarkers/Generic/SingleDrumRoller_noncat_MapMarker.png",
  	"iconImageFolder": "images/AssetIcons", "iconFileName": "SingleDrumRoller_non-cat.png", "OEMIconFileName": "CATHeaderLogo_SM.png"},
  { "iconID": 54, "width": 70, "height": 44, "originX": 0, "originY": 0, "anchorX": 0, "anchorY": 44, "markerImgUrl": "images/AssetMapMarkers/Generic/Skidder_noncat_MapMarker.png",
  	"iconImageFolder": "images/AssetIcons", "iconFileName": "Skidder_non-cat.png", "OEMIconFileName": "CATHeaderLogo_SM.png"},
  { "iconID": 55, "width": 66, "height": 44, "originX": 0, "originY": 0, "anchorX": 0, "anchorY": 44, "markerImgUrl": "images/AssetMapMarkers/Generic/SkidSteerLoader_noncat_MapMarker.png",
  	"iconImageFolder": "images/AssetIcons", "iconFileName": "SkidSteerLoader_non-cat.png", "OEMIconFileName": "CATHeaderLogo_SM.png"},
  { "iconID": 56, "width": 70, "height": 44, "originX": 0, "originY": 0, "anchorX": 0, "anchorY": 44, "markerImgUrl": "images/AssetMapMarkers/Generic/Telehandler_noncat_MapMarker.png",
  	"iconImageFolder": "images/AssetIcons", "iconFileName": "Telehandler_non-cat.png", "OEMIconFileName": "CATHeaderLogo_SM.png"},
  { "iconID": 57, "width": 70, "height": 44, "originX": 0, "originY": 0, "anchorX": 0, "anchorY": 44, "markerImgUrl": "images/AssetMapMarkers/Generic/TrackLoader_noncat_MapMarker.png",
  	"iconImageFolder": "images/AssetIcons", "iconFileName": "TrackLoader_non-cat.png", "OEMIconFileName": "CATHeaderLogo_SM.png"},
  { "iconID": 58, "width": 66, "height": 44, "originX": 0, "originY": 0, "anchorX": 0, "anchorY": 44, "markerImgUrl": "images/AssetMapMarkers/Generic/TrackTypeTractor_noncat_MapMarker.png",
  	"iconImageFolder": "images/AssetIcons", "iconFileName": "TrackTypeTractor_non-cat.png", "OEMIconFileName": "CATHeaderLogo_SM.png"},
  { "iconID": 59, "width": 74, "height": 44, "originX": 0, "originY": 0, "anchorX": 0, "anchorY": 44, "markerImgUrl": "images/AssetMapMarkers/Generic/TractorTrailer_noncat_MapMarker.png",
  	"iconImageFolder": "images/AssetIcons", "iconFileName": "TractorTrailer_non-cat.png", "OEMIconFileName": "CATHeaderLogo_SM.png"},
  { "iconID": 60, "width": 74, "height": 44, "originX": 0, "originY": 0, "anchorX": 0, "anchorY": 44, "markerImgUrl": "images/AssetMapMarkers/Generic/UndergroundMining_noncat_MapMarker.png",
  	"iconImageFolder": "images/AssetIcons", "iconFileName": "UndergroundMining_non-cat.png", "OEMIconFileName": "CATHeaderLogo_SM.png"},
  { "iconID": 61, "width": 70, "height": 44, "originX": 0, "originY": 0, "anchorX": 0, "anchorY": 44, "markerImgUrl": "images/AssetMapMarkers/Generic/WheelDozer_noncat_MapMarker.png",
  	"iconImageFolder": "images/AssetIcons", "iconFileName": "WheelDozer_non-cat.png", "OEMIconFileName": "CATHeaderLogo_SM.png"},
  { "iconID": 62, "width": 70, "height": 44, "originX": 0, "originY": 0, "anchorX": 0, "anchorY": 44, "markerImgUrl": "images/AssetMapMarkers/Generic/WheelExcavator_noncat_MapMarker.png",
  	"iconImageFolder": "images/AssetIcons", "iconFileName": "WheelExcavator_non-cat.png", "OEMIconFileName": "CATHeaderLogo_SM.png"},
  { "iconID": 63, "width": 70, "height": 44, "originX": 0, "originY": 0, "anchorX": 0, "anchorY": 44, "markerImgUrl": "images/AssetMapMarkers/Generic/WheelLoader_noncat_MapMarker.png",
  	"iconImageFolder": "images/AssetIcons", "iconFileName": "WheelLoader_non-cat.png", "OEMIconFileName": "CATHeaderLogo_SM.png"},
  { "iconID": 64, "width": 74, "height": 44, "originX": 0, "originY": 0, "anchorX": 0, "anchorY": 44, "markerImgUrl": "images/AssetMapMarkers/Generic/WheelTractorScraper_noncat_MapMarker.png",
  	"iconImageFolder": "images/AssetIcons", "iconFileName": "WheelTractorScraper_non-cat.png", "OEMIconFileName": "CATHeaderLogo_SM.png"},
  { "iconID": 65, "width": 74, "height": 44, "originX": 0, "originY": 0, "anchorX": 0, "anchorY": 44, "markerImgUrl": "images/AssetMapMarkers/Generic/WheelTractorScrapers_noncat_MapMarker.png",
  	"iconImageFolder": "images/AssetIcons", "iconFileName": "WheelTractorScrapers_non-cat.png", "OEMIconFileName": "CATHeaderLogo_SM.png"},
  { "iconID": 66, "width": 70, "height": 44, "originX": 0, "originY": 0, "anchorX": 0, "anchorY": 44, "markerImgUrl": "images/AssetMapMarkers/Generic/Pickup_noncat_MapMarker.png",
  	"iconImageFolder": "images/AssetIcons", "iconFileName": "Pickup_non-cat.png", "OEMIconFileName": "CATHeaderLogo_SM.png"},
  { "iconID": 67, "width": 66, "height": 44, "originX": 0, "originY": 0, "anchorX": 0, "anchorY": 44, "markerImgUrl": "images/AssetMapMarkers/Generic/FlagBlue_noncat_MapMarker.png",
  	"iconImageFolder": "images/AssetIcons", "iconFileName": "FlagBlue_non-cat.png", "OEMIconFileName": "CATHeaderLogo_SM.png"},
  { "iconID": 68, "width": 66, "height": 44, "originX": 0, "originY": 0, "anchorX": 0, "anchorY": 44, "markerImgUrl": "images/AssetMapMarkers/Generic/FlagWhite_noncat_MapMarker.png",
  	"iconImageFolder": "images/AssetIcons", "iconFileName": "FlagWhite_non-cat.png", "OEMIconFileName": "CATHeaderLogo_SM.png"},
  { "iconID": 69, "width": 66, "height": 44, "originX": 0, "originY": 0, "anchorX": 0, "anchorY": 44, "markerImgUrl": "images/AssetMapMarkers/Generic/FlagYellow_noncat_MapMarker.png",
  	"iconImageFolder": "images/AssetIcons", "iconFileName": "FlagYellow_non-cat.png", "OEMIconFileName": "CATHeaderLogo_SM.png"},
  { "iconID": 70, "width": 66, "height": 44, "originX": 0, "originY": 0, "anchorX": 0, "anchorY": 44, "markerImgUrl": "images/AssetMapMarkers/Generic/TriangleBlue_noncat_MapMarker.png",
  	"iconImageFolder": "images/AssetIcons", "iconFileName": "TriangleBlue_non-cat.png", "OEMIconFileName": "CATHeaderLogo_SM.png"},
  { "iconID": 71, "width": 66, "height": 44, "originX": 0, "originY": 0, "anchorX": 0, "anchorY": 44, "markerImgUrl": "images/AssetMapMarkers/Generic/TriangleWhite_noncat_MapMarker.png",
  	"iconImageFolder": "images/AssetIcons", "iconFileName": "TriangleWhite_non-cat.png", "OEMIconFileName": "CATHeaderLogo_SM.png"},
  { "iconID": 72, "width": 66, "height": 44, "originX": 0, "originY": 0, "anchorX": 0, "anchorY": 44, "markerImgUrl": "images/AssetMapMarkers/Generic/TriangleYellow_noncat_MapMarker.png",
  	"iconImageFolder": "images/AssetIcons", "iconFileName": "TriangleYellow_non-cat.png", "OEMIconFileName": "CATHeaderLogo_SM.png"},
  { "iconID": 73, "width": 74, "height": 44, "originX": 0, "originY": 0, "anchorX": 0, "anchorY": 44, "markerImgUrl": "images/AssetMapMarkers/CAT/CatTruck_MapMarker.png",
  	"iconImageFolder": "images/AssetIcons", "iconFileName": "CatTruck.png", "OEMIconFileName": "CATHeaderLogo_SM.png"},
  { "iconID": 74, "width": 70, "height": 44, "originX": 0, "originY": 0, "anchorX": 0, "anchorY": 44, "markerImgUrl": "images/AssetMapMarkers/CAT/CatTruckDefault_MapMarker.png",
  	"iconImageFolder": "images/AssetIcons", "iconFileName": "CatTruckDefault.png", "OEMIconFileName": "CATHeaderLogo_SM.png"},
  { "iconID": 75, "width": 74, "height": 44, "originX": 0, "originY": 0, "anchorX": 0, "anchorY": 44, "markerImgUrl": "images/AssetMapMarkers/CAT/ConcreteMixer_MapMarker.png",
  	"iconImageFolder": "images/AssetIcons", "iconFileName": "ConcreteMixer.png", "OEMIconFileName": "CATHeaderLogo_SM.png"},
  { "iconID": 76, "width": 70, "height": 44, "originX": 0, "originY": 0, "anchorX": 0, "anchorY": 44, "markerImgUrl": "images/AssetMapMarkers/Generic/GeneratorSet1_noncat_MapMarker.png",
  	"iconImageFolder": "images/AssetIcons", "iconFileName": "GeneratorSet1_non-cat.png", "OEMIconFileName": "CATHeaderLogo_SM.png"},
  { "iconID": 77, "width": 70, "height": 44, "originX": 0, "originY": 0, "anchorX": 0, "anchorY": 44, "markerImgUrl": "images/AssetMapMarkers/Generic/GeneratorSet2_noncat_MapMarker.png",
  	"iconImageFolder": "images/AssetIcons", "iconFileName": "GeneratorSet2_non-cat.png", "OEMIconFileName": "CATHeaderLogo_SM.png"},
  { "iconID": 78, "width": 70, "height": 44, "originX": 0, "originY": 0, "anchorX": 0, "anchorY": 44, "markerImgUrl": "images/AssetMapMarkers/Generic/GeneratorSet3_noncat_MapMarker.png",
  	"iconImageFolder": "images/AssetIcons", "iconFileName": "GeneratorSet3_non-cat.png", "OEMIconFileName": "CATHeaderLogo_SM.png"},
  { "iconID": 79, "width": 66, "height": 44, "originX": 0, "originY": 0, "anchorX": 0, "anchorY": 44, "markerImgUrl": "images/AssetMapMarkers/Generic/RentalGeneratorSet1_noncat_MapMarker.png",
  	"iconImageFolder": "images/AssetIcons", "iconFileName": "RentalGeneratorSet1_non-cat.png", "OEMIconFileName": "CATHeaderLogo_SM.png"},
  { "iconID": 80, "width": 70, "height": 44, "originX": 0, "originY": 0, "anchorX": 0, "anchorY": 44, "markerImgUrl": "images/AssetMapMarkers/Generic/RentalGeneratorSet2_noncat_MapMarker.png",
  	"iconImageFolder": "images/AssetIcons", "iconFileName": "RentalGeneratorSet2_non-cat.png", "OEMIconFileName": "CATHeaderLogo_SM.png"},
  { "iconID": 81, "width": 70, "height": 44, "originX": 0, "originY": 0, "anchorX": 0, "anchorY": 44, "markerImgUrl": "images/AssetMapMarkers/CAT/CatTruckDefault_MapMarker.png",
  	"iconImageFolder": "images/AssetIcons", "iconFileName": "CatTruckDefault.png", "OEMIconFileName": "CATHeaderLogo_SM.png"},
  { "iconID": 82, "width": 66, "height": 44, "originX": 0, "originY": 0, "anchorX": 0, "anchorY": 44, "markerImgUrl": "images/AssetMapMarkers/CAT/HydraulicExcavatorMini_MapMarker.png",
  	"iconImageFolder": "images/AssetIcons", "iconFileName": "hydraulicExcavatorMini.png", "OEMIconFileName": "CATHeaderLogo_SM.png"},
  { "iconID": 83, "width": 66, "height": 44, "originX": 0, "originY": 0, "anchorX": 0, "anchorY": 44, "markerImgUrl": "images/AssetMapMarkers/CAT/PneumaticTiredCompactor_MapMarker.png",
  	"iconImageFolder": "images/AssetIcons", "iconFileName": "PneumaticTiredCompactor.png", "OEMIconFileName": "CATHeaderLogo_SM.png"},
  { "iconID": 84, "width": 70, "height": 44, "originX": 0, "originY": 0, "anchorX": 0, "anchorY": 44, "markerImgUrl": "images/AssetMapMarkers/CAT/Tractor_MapMarker.png",
  	"iconImageFolder": "images/AssetIcons", "iconFileName": "Tractor.png", "OEMIconFileName": "CATHeaderLogo_SM.png"},
  { "iconID": 85, "width": 66, "height": 44, "originX": 0, "originY": 0, "anchorX": 0, "anchorY": 44, "markerImgUrl": "images/AssetMapMarkers/CAT/TrackTypeTractorsOvalTrack_MapMarker.png",
  	"iconImageFolder": "images/AssetIcons", "iconFileName": "TrackTypeTractorsOvalTrack.png", "OEMIconFileName": "CATHeaderLogo_SM.png"},
  { "iconID": 86, "width": 66, "height": 44, "originX": 0, "originY": 0, "anchorX": 0, "anchorY": 44, "markerImgUrl": "images/AssetMapMarkers/CAT/UtilityCompactor_MapMarker.png",
  	"iconImageFolder": "images/AssetIcons", "iconFileName": "UtilityCompactor.png", "OEMIconFileName": "CATHeaderLogo_SM.png"},
  { "iconID": 87, "width": 66, "height": 44, "originX": 0, "originY": 0, "anchorX": 0, "anchorY": 44, "markerImgUrl": "images/AssetMapMarkers/CAT/VibratoryDoubleDrumCompactor_MapMarker.png",
  	"iconImageFolder": "images/AssetIcons", "iconFileName": "VibratoryDoubleDrumCompactor.png", "OEMIconFileName": "CATHeaderLogo_SM.png"},
  { "iconID": 88, "width": 66, "height": 44, "originX": 0, "originY": 0, "anchorX": 0, "anchorY": 44, "markerImgUrl": "images/AssetMapMarkers/CAT/VibratorySingleDrumCompactor_MapMarker.png",
  	"iconImageFolder": "images/AssetIcons", "iconFileName": "VibratorySingleDrumCompactor.png", "OEMIconFileName": "CATHeaderLogo_SM.png"},
  { "iconID": 89, "width": 70, "height": 44, "originX": 0, "originY": 0, "anchorX": 0, "anchorY": 44, "markerImgUrl": "images/AssetMapMarkers/Generic/AgriculturalTractor1_MapMarker.png",
  	"iconImageFolder": "images/AssetIcons", "iconFileName": "AgriculturalTractor1.png", "OEMIconFileName": "CATHeaderLogo_SM.png"},
  { "iconID": 90, "width": 70, "height": 44, "originX": 0, "originY": 0, "anchorX": 0, "anchorY": 44, "markerImgUrl": "images/AssetMapMarkers/Generic/AgriculturalTractor2_MapMarker.png",
  	"iconImageFolder": "images/AssetIcons", "iconFileName": "AgriculturalTractor2.png", "OEMIconFileName": "CATHeaderLogo_SM.png"},
  { "iconID": 91, "width": 70, "height": 44, "originX": 0, "originY": 0, "anchorX": 0, "anchorY": 44, "markerImgUrl": "images/AssetMapMarkers/Generic/FishingVessel_MapMarker.png",
  	"iconImageFolder": "images/AssetIcons", "iconFileName": "FishingVessel.png", "OEMIconFileName": "CATHeaderLogo_SM.png"},
  { "iconID": 92, "width": 74, "height": 44, "originX": 0, "originY": 0, "anchorX": 0, "anchorY": 44, "markerImgUrl": "images/AssetMapMarkers/Generic/Locomotive_MapMarker.png",
  	"iconImageFolder": "images/AssetIcons", "iconFileName": "Locomotive.png", "OEMIconFileName": "CATHeaderLogo_SM.png"},
  { "iconID": 93, "width": 74, "height": 44, "originX": 0, "originY": 0, "anchorX": 0, "anchorY": 44, "markerImgUrl": "images/AssetMapMarkers/Generic/PleasureCraft_MapMarker.png",
  	"iconImageFolder": "images/AssetIcons", "iconFileName": "PleasureCraft.png", "OEMIconFileName": "CATHeaderLogo_SM.png"},
  { "iconID": 94, "width": 70, "height": 44, "originX": 0, "originY": 0, "anchorX": 0, "anchorY": 44, "markerImgUrl": "images/AssetMapMarkers/Generic/TugVessel_MapMarker.png",
  	"iconImageFolder": "images/AssetIcons", "iconFileName": "TugVessel.png", "OEMIconFileName": "CATHeaderLogo_SM.png"},
  { "iconID": 95, "width": 74, "height": 44, "originX": 0, "originY": 0, "anchorX": 0, "anchorY": 44, "markerImgUrl": "images/AssetMapMarkers/Generic/TerrainLeveler_noncat_MapMarker.png",
  	"iconImageFolder": "images/AssetIcons", "iconFileName": "TerrainLeveler_non-cat.png", "OEMIconFileName": "CATHeaderLogo_SM.png"},
  { "iconID": 96, "width": 70, "height": 44, "originX": 0, "originY": 0, "anchorX": 0, "anchorY": 44, "markerImgUrl": "images/AssetMapMarkers/Generic/Drill_noncat_MapMarker.png",
  	"iconImageFolder": "images/AssetIcons", "iconFileName": "Drill_lrg_non-cat.png", "OEMIconFileName": "CATHeaderLogo_SM.png"},
  { "iconID": 97, "width": 66, "height": 44, "originX": 0, "originY": 0, "anchorX": 0, "anchorY": 44, "markerImgUrl": "images/AssetMapMarkers/Generic/PileDriver_noncat_MapMarker.png",
  	"iconImageFolder": "images/AssetIcons", "iconFileName": "PileDriver_lrg_non-cat.png", "OEMIconFileName": "CATHeaderLogo_SM.png"},
  { "iconID": 99, "width": 66, "height": 44, "originX": 0, "originY": 0, "anchorX": 0, "anchorY": 44, "markerImgUrl": "images/AssetMapMarkers/CAT/Forklift_MapMarker.png",
  	"iconImageFolder": "images/AssetIcons", "iconFileName": "forkLift_lrg.png", "OEMIconFileName": "CATHeaderLogo_SM.png"},
  { "iconID": 100, "width": 70, "height": 44, "originX": 0, "originY": 0, "anchorX": 0, "anchorY": 44, "markerImgUrl": "images/AssetMapMarkers/Generic/PaverAsphalt_noncat_MapMarker.png",
  	"iconImageFolder": "images/AssetIcons", "iconFileName": "PaverAsphalt_lrg_non-cat.png", "OEMIconFileName": "CATHeaderLogo_SM.png"},
  { "iconID": 101, "width": 70, "height": 44, "originX": 0, "originY": 0, "anchorX": 0, "anchorY": 44, "markerImgUrl": "images/AssetMapMarkers/Generic/PaverConcrete_noncat_MapMarker.png",
  	"iconImageFolder": "images/AssetIcons", "iconFileName": "PaverConcrete_lrg_non-cat.png", "OEMIconFileName": "CATHeaderLogo_SM.png"},
  { "iconID": 102, "width": 66, "height": 44, "originX": 0, "originY": 0, "anchorX": 0, "anchorY": 44, "markerImgUrl": "images/AssetMapMarkers/CAT/3512_MapMarker.png",
  	"iconImageFolder": "images/AssetIcons", "iconFileName": "3512_lrg.png", "OEMIconFileName": "CATHeaderLogo_SM.png"},
  { "iconID": 103, "width": 66, "height": 44, "originX": 0, "originY": 0, "anchorX": 0, "anchorY": 44, "markerImgUrl": "images/AssetMapMarkers/CAT/C9_MapMarker.png",
  	"iconImageFolder": "images/AssetIcons", "iconFileName": "c9_lrg.png", "OEMIconFileName": "CATHeaderLogo_SM.png"},
  { "iconID": 104, "width": 66, "height": 44, "originX": 0, "originY": 0, "anchorX": 0, "anchorY": 44, "markerImgUrl": "images/AssetMapMarkers/CAT/C32_MapMarker.png",
  	"iconImageFolder": "images/AssetIcons", "iconFileName": "c32_lrg.png", "OEMIconFileName": "CATHeaderLogo_SM.png"},
  { "iconID": 105, "width": 70, "height": 44, "originX": 0, "originY": 0, "anchorX": 0, "anchorY": 44, "markerImgUrl": "images/AssetMapMarkers/Generic/TH76_noncat_MapMarker.png",
  	"iconImageFolder": "images/AssetIcons", "iconFileName": "TH-76_lrg_non-cat.png", "OEMIconFileName": "CATHeaderLogo_SM.png"},
  { "iconID": 106, "width": 70, "height": 44, "originX": 0, "originY": 0, "anchorX": 0, "anchorY": 44, "markerImgUrl": "images/AssetMapMarkers/Generic/TH86_noncat_MapMarker.png",
  	"iconImageFolder": "images/AssetIcons", "iconFileName": "TH-86_lrg_non-cat.png", "OEMIconFileName": "CATHeaderLogo_SM.png"},

  	
  { "iconID": 107, "width": 66, "height": 44, "originX": 0, "originY": 0, "anchorX": 0, "anchorY": 44, "markerImgUrl": "images/AssetMapMarkers/Generic/EX200LCH_thc_non-cat_MapMarker.png",
  	"iconImageFolder": "images/AssetIcons", "iconFileName": "EX200LCH_thc_non-cat.png", "OEMIconFileName": "CATHeaderLogo_SM.png"},
  { "iconID": 108, "width": 66, "height": 44, "originX": 0, "originY": 0, "anchorX": 0, "anchorY": 44, "markerImgUrl": "images/AssetMapMarkers/Generic/EX110_thc_non-cat_MapMarker.png",
  	"iconImageFolder": "images/AssetIcons", "iconFileName": "EX110_thc_non-cat.png", "OEMIconFileName": "CATHeaderLogo_SM.png"},
  { "iconID": 109, "width": 66, "height": 44, "originX": 0, "originY": 0, "anchorX": 0, "anchorY": 44, "markerImgUrl": "images/AssetMapMarkers/Generic/EX70_thc_non-cat_MapMarker.png",
  	"iconImageFolder": "images/AssetIcons", "iconFileName": "EX70_thc_non-cat.png", "OEMIconFileName": "CATHeaderLogo_SM.png"},
  { "iconID": 110, "width": 70, "height": 44, "originX": 0, "originY": 0, "anchorX": 0, "anchorY": 44, "markerImgUrl": "images/AssetMapMarkers/Generic/MotorGrader_lby_non-cat_MapMarker.png",
  	"iconImageFolder": "images/AssetIcons", "iconFileName": "MotorGrader_lby_non-cat.png", "OEMIconFileName": "CATHeaderLogo_SM.png"},
  { "iconID": 111, "width": 66, "height": 44, "originX": 0, "originY": 0, "anchorX": 0, "anchorY": 44, "markerImgUrl": "images/AssetMapMarkers/Generic/BackhoeLoader_lby_non-cat_MapMarker.png",
  	"iconImageFolder": "images/AssetIcons", "iconFileName": "BackhoeLoader_lby_non-cat.png", "OEMIconFileName": "CATHeaderLogo_SM.png"},
  { "iconID": 112, "width": 70, "height": 44, "originX": 0, "originY": 0, "anchorX": 0, "anchorY": 44, "markerImgUrl": "images/AssetMapMarkers/Generic/Excavator_lby_non-cat_MapMarker.png",
  	"iconImageFolder": "images/AssetIcons", "iconFileName": "Excavator_lby_non-cat.png", "OEMIconFileName": "CATHeaderLogo_SM.png"},
  { "iconID": 113, "width": 66, "height": 44, "originX": 0, "originY": 0, "anchorX": 0, "anchorY": 44, "markerImgUrl": "images/AssetMapMarkers/Generic/A8800_cih_non-cat_MapMarker.png",
  	"iconImageFolder": "images/AssetIcons", "iconFileName": "A8800_cih_non-cat.png", "OEMIconFileName": "CATHeaderLogo_SM.png"},
  { "iconID": 114, "width": 70, "height": 44, "originX": 0, "originY": 0, "anchorX": 0, "anchorY": 44, "markerImgUrl": "images/AssetMapMarkers/Generic/Combine_cih_non-cat_MapMarker.png",
  	"iconImageFolder": "images/AssetIcons", "iconFileName": "Combine_cih_non-cat.png", "OEMIconFileName": "CATHeaderLogo_SM.png"},
  { "iconID": 115, "width": 66, "height": 44, "originX": 0, "originY": 0, "anchorX": 0, "anchorY": 44, "markerImgUrl": "images/AssetMapMarkers/Generic/CPX420_cih_non-cat_MapMarker.png",
  	"iconImageFolder": "images/AssetIcons", "iconFileName": "CPX420_cih_non-cat.png", "OEMIconFileName": "CATHeaderLogo_SM.png"},
  { "iconID": 116, "width": 66, "height": 44, "originX": 0, "originY": 0, "anchorX": 0, "anchorY": 44, "markerImgUrl": "images/AssetMapMarkers/Generic/Farmall_cih_non-cat_MapMarker.png",
  	"iconImageFolder": "images/AssetIcons", "iconFileName": "Farmall_cih_non-cat.png", "OEMIconFileName": "CATHeaderLogo_SM.png"},
  { "iconID": 117, "width": 66, "height": 44, "originX": 0, "originY": 0, "anchorX": 0, "anchorY": 44, "markerImgUrl": "images/AssetMapMarkers/Generic/Magnum_cih_non-cat_MapMarker.png",
  	"iconImageFolder": "images/AssetIcons", "iconFileName": "Magnum_cih_non-cat.png", "OEMIconFileName": "CATHeaderLogo_SM.png"},
  { "iconID": 118, "width": 66, "height": 44, "originX": 0, "originY": 0, "anchorX": 0, "anchorY": 44, "markerImgUrl": "images/AssetMapMarkers/Generic/Maxxum_cih_non-cat_MapMarker.png",
  	"iconImageFolder": "images/AssetIcons", "iconFileName": "Maxxum_cih_non-cat.png", "OEMIconFileName": "CATHeaderLogo_SM.png"},
  { "iconID": 119, "width": 70, "height": 44, "originX": 0, "originY": 0, "anchorX": 0, "anchorY": 44, "markerImgUrl": "images/AssetMapMarkers/Generic/Patriot_Sprayer_cih_non-cat_MapMarker.png",
  	"iconImageFolder": "images/AssetIcons", "iconFileName": "Patriot_Sprayer_cih_non-cat.png", "OEMIconFileName": "CATHeaderLogo_SM.png"},
  { "iconID": 120, "width": 66, "height": 44, "originX": 0, "originY": 0, "anchorX": 0, "anchorY": 44, "markerImgUrl": "images/AssetMapMarkers/Generic/Puma_cih_non-cat_MapMarker.png",
  	"iconImageFolder": "images/AssetIcons", "iconFileName": "Puma_cih_non-cat.png", "OEMIconFileName": "CATHeaderLogo_SM.png"},
  { "iconID": 121, "width": 66, "height": 44, "originX": 0, "originY": 0, "anchorX": 0, "anchorY": 44, "markerImgUrl": "images/AssetMapMarkers/Generic/Steiger_cih_non-cat_MapMarker.png",
  	"iconImageFolder": "images/AssetIcons", "iconFileName": "Steiger_cih_non-cat.png", "OEMIconFileName": "CATHeaderLogo_SM.png"},
  { "iconID": 122, "width": 66, "height": 44, "originX": 0, "originY": 0, "anchorX": 0, "anchorY": 44, "markerImgUrl": "images/AssetMapMarkers/Generic/Steiger_QuadTrac_cih_non-cat_MapMarker.png",
  	"iconImageFolder": "images/AssetIcons", "iconFileName": "Steiger_QuadTrac_cih_non-cat.png", "OEMIconFileName": "CATHeaderLogo_SM.png"},
  { "iconID": 123, "width": 66, "height": 44, "originX": 0, "originY": 0, "anchorX": 0, "anchorY": 44, "markerImgUrl": "images/AssetMapMarkers/Generic/Titan_Floater_cih_non-cat_MapMarker.png",
  	"iconImageFolder": "images/AssetIcons", "iconFileName": "Titan_Floater_cih_non-cat.png", "OEMIconFileName": "CATHeaderLogo_SM.png"},
  { "iconID": 124, "width": 66, "height": 44, "originX": 0, "originY": 0, "anchorX": 0, "anchorY": 44, "markerImgUrl": "images/AssetMapMarkers/Generic/CR9090_nh_non-cat_MapMarker.png",
  	"iconImageFolder": "images/AssetIcons", "iconFileName": "CR9090_nh_non-cat.png", "OEMIconFileName": "CATHeaderLogo_SM.png"},
  { "iconID": 125, "width": 66, "height": 44, "originX": 0, "originY": 0, "anchorX": 0, "anchorY": 44, "markerImgUrl": "images/AssetMapMarkers/Generic/CX8090_nh_non-cat_MapMarker.png",
  	"iconImageFolder": "images/AssetIcons", "iconFileName": "CX8090_nh_non-cat.png", "OEMIconFileName": "CATHeaderLogo_SM.png"},
  { "iconID": 126, "width": 66, "height": 44, "originX": 0, "originY": 0, "anchorX": 0, "anchorY": 44, "markerImgUrl": "images/AssetMapMarkers/Generic/ForageHarvester_nh_non-cat_MapMarker.png",
  	"iconImageFolder": "images/AssetIcons", "iconFileName": "ForageHarvester_nh_non-cat.png", "OEMIconFileName": "CATHeaderLogo_SM.png"},
  { "iconID": 127, "width": 66, "height": 44, "originX": 0, "originY": 0, "anchorX": 0, "anchorY": 44, "markerImgUrl": "images/AssetMapMarkers/Generic/GrapeHarvester_nh_non-cat_MapMarker.png",
  	"iconImageFolder": "images/AssetIcons", "iconFileName": "GrapeHarvester_nh_non-cat.png", "OEMIconFileName": "CATHeaderLogo_SM.png"},
  { "iconID": 128, "width": 66, "height": 44, "originX": 0, "originY": 0, "anchorX": 0, "anchorY": 44, "markerImgUrl": "images/AssetMapMarkers/Generic/Guardian_nh_non-cat_MapMarker.png",
  	"iconImageFolder": "images/AssetIcons", "iconFileName": "Guardian_nh_non-cat.png", "OEMIconFileName": "CATHeaderLogo_SM.png"},
  { "iconID": 129, "width": 66, "height": 44, "originX": 0, "originY": 0, "anchorX": 0, "anchorY": 44, "markerImgUrl": "images/AssetMapMarkers/Generic/T5_nh_non-cat_MapMarker.png",
  	"iconImageFolder": "images/AssetIcons", "iconFileName": "T5_nh_non-cat.png", "OEMIconFileName": "CATHeaderLogo_SM.png"},
  { "iconID": 130, "width": 66, "height": 44, "originX": 0, "originY": 0, "anchorX": 0, "anchorY": 44, "markerImgUrl": "images/AssetMapMarkers/Generic/T6_nh_non-cat_MapMarker.png",
  	"iconImageFolder": "images/AssetIcons", "iconFileName": "T6_nh_non-cat.png", "OEMIconFileName": "CATHeaderLogo_SM.png"},
  { "iconID": 131, "width": 66, "height": 44, "originX": 0, "originY": 0, "anchorX": 0, "anchorY": 44, "markerImgUrl": "images/AssetMapMarkers/Generic/T7_270_nh_non-cat_MapMarker.png",
  	"iconImageFolder": "images/AssetIcons", "iconFileName": "T7_270_nh_non-cat.png", "OEMIconFileName": "CATHeaderLogo_SM.png"},
  { "iconID": 132, "width": 66, "height": 44, "originX": 0, "originY": 0, "anchorX": 0, "anchorY": 44, "markerImgUrl": "images/AssetMapMarkers/Generic/T8_390_nh_non-cat_MapMarker.png",
  	"iconImageFolder": "images/AssetIcons", "iconFileName": "T8_390_nh_non-cat.png", "OEMIconFileName": "CATHeaderLogo_SM.png"},
  { "iconID": 133, "width": 66, "height": 44, "originX": 0, "originY": 0, "anchorX": 0, "anchorY": 44, "markerImgUrl": "images/AssetMapMarkers/Generic/T9_670_nh_non-cat_MapMarker.png",
  	"iconImageFolder": "images/AssetIcons", "iconFileName": "T9_670_nh_non-cat.png", "OEMIconFileName": "CATHeaderLogo_SM.png"},
  { "iconID": 134, "width": 66, "height": 44, "originX": 0, "originY": 0, "anchorX": 0, "anchorY": 44, "markerImgUrl": "images/AssetMapMarkers/Generic/TC5070_nh_non-cat_MapMarker.png",
  	"iconImageFolder": "images/AssetIcons", "iconFileName": "TC5070_nh_non-cat.png", "OEMIconFileName": "CATHeaderLogo_SM.png"},
  { "iconID": 135, "width": 66, "height": 44, "originX": 0, "originY": 0, "anchorX": 0, "anchorY": 44, "markerImgUrl": "images/AssetMapMarkers/Generic/DX210_dsn_non-cat_MapMarker.png",
  	"iconImageFolder": "images/AssetIcons", "iconFileName": "DX210_dsn_non-cat.png", "OEMIconFileName": "CATHeaderLogo_SM.png"},
  { "iconID": 136, "width": 66, "height": 44, "originX": 0, "originY": 0, "anchorX": 0, "anchorY": 44, "markerImgUrl": "images/AssetMapMarkers/Generic/DX225_dsn_non-cat_MapMarker.png",
  	"iconImageFolder": "images/AssetIcons", "iconFileName": "DX225_dsn_non-cat.png", "OEMIconFileName": "CATHeaderLogo_SM.png"},
  { "iconID": 137, "width": 66, "height": 44, "originX": 0, "originY": 0, "anchorX": 0, "anchorY": 44, "markerImgUrl": "images/AssetMapMarkers/Generic/DX340_dsn_non-cat_MapMarker.png",
  	"iconImageFolder": "images/AssetIcons", "iconFileName": "DX340_dsn_non-cat.png", "OEMIconFileName": "CATHeaderLogo_SM.png"},
  { "iconID": 138, "width": 66, "height": 44, "originX": 0, "originY": 0, "anchorX": 0, "anchorY": 44, "markerImgUrl": "images/AssetMapMarkers/Generic/S150_dsn_non-cat_MapMarker.png",
  	"iconImageFolder": "images/AssetIcons", "iconFileName": "S150_dsn_non-cat.png", "OEMIconFileName": "CATHeaderLogo_SM.png"},
  { "iconID": 139, "width": 66, "height": 44, "originX": 0, "originY": 0, "anchorX": 0, "anchorY": 44, "markerImgUrl": "images/AssetMapMarkers/Generic/S300_dsn_non-cat_MapMarker.png",
  	"iconImageFolder": "images/AssetIcons", "iconFileName": "S300_dsn_non-cat.png", "OEMIconFileName": "CATHeaderLogo_SM.png"},
  { "iconID": 140, "width": 66, "height": 44, "originX": 0, "originY": 0, "anchorX": 0, "anchorY": 44, "markerImgUrl": "images/AssetMapMarkers/Generic/S500_dsn_non-cat_MapMarker.png",
  	"iconImageFolder": "images/AssetIcons", "iconFileName": "S500_dsn_non-cat.png", "OEMIconFileName": "CATHeaderLogo_SM.png"},
  { "iconID": 141, "width": 66, "height": 44, "originX": 0, "originY": 0, "anchorX": 0, "anchorY": 44, "markerImgUrl": "images/AssetMapMarkers/Generic/SP_Sprayer_nh_non-cat_MapMarker.png",
  	"iconImageFolder": "images/AssetIcons", "iconFileName": "SP_Sprayer_nh_non-cat.png", "OEMIconFileName": "CATHeaderLogo_SM.png"},
  { "iconID": 142, "width": 66, "height": 44, "originX": 0, "originY": 0, "anchorX": 0, "anchorY": 44, "markerImgUrl": "images/AssetMapMarkers/Generic/S80_dsn_non-cat_MapMarker.png",
  	"iconImageFolder": "images/AssetIcons", "iconFileName": "S80_dsn_non-cat.png", "OEMIconFileName": "CATHeaderLogo_SM.png"},
  { "iconID": 143, "width": 85, "height": 44, "originX": 0, "originY": 0, "anchorX": 0, "anchorY": 44, "markerImgUrl": "images/AssetMapMarkers/Generic/S340_dsn_non-cat_MapMarker.png",
  	"iconImageFolder": "images/AssetIcons", "iconFileName": "S340_dsn_non-cat.png", "OEMIconFileName": "CATHeaderLogo_SM.png"},
  { "iconID": 144, "width": 85, "height": 44, "originX": 0, "originY": 0, "anchorX": 0, "anchorY": 44, "markerImgUrl": "images/AssetMapMarkers/Generic/DX300_dsn_non-cat_MapMarker.png",
  	"iconImageFolder": "images/AssetIcons", "iconFileName": "DX300_dsn_non-cat.png", "OEMIconFileName": "CATHeaderLogo_SM.png"},
  { "iconID": 145, "width": 66, "height": 44, "originX": 0, "originY": 0, "anchorX": 0, "anchorY": 44, "markerImgUrl": "images/AssetMapMarkers/Generic/CSCombine_nh_non-cat_MapMarker.png",
  	"iconImageFolder": "images/AssetIcons", "iconFileName": "CSCombine_nh_non-cat.png", "OEMIconFileName": "CATHeaderLogo_SM.png"},
  { "iconID": 146, "width": 66, "height": 44, "originX": 0, "originY": 0, "anchorX": 0, "anchorY": 44, "markerImgUrl": "images/AssetMapMarkers/Generic/T4_nh_non-cat_MapMarker.png",
  	"iconImageFolder": "images/AssetIcons", "iconFileName": "T4_nh_non-cat.png", "OEMIconFileName": "CATHeaderLogo_SM.png"}

  	];

  //Private function



  //Public Property

  namespace.closeIconURL = "images/AssetMapMarkers/closearrow.png";

  //Public Methods
  namespace.getAssetMarker = function (iconID) {
    var val = $.grep(markerCatalog, function (n, i) {
      return n.iconID == iconID;
    });

    if (val.length == 1) {
      return val[0];
    }
    else {
      return null;
    }
  };

  namespace.getAssetIcon = function (iconID) {
    var val = $.grep(markerCatalog, function (n, i) {
      return n.iconID == iconID;
    });

    if (val.length == 1) {
      return val[0].iconImageFolder + "/" + val[0].iconFileName;
    }
    else {
      return undefined;
    }
  };

  namespace.getAssetOEMIcon = function (iconID) {
    var val = $.grep(markerCatalog, function (n, i) {
      return n.iconID == iconID;
    });

    if (val.length == 1) {
      return val[0].iconImageFolder + "/" + val[0].OEMIconFileName;
    }
    else {
      return undefined;
    }
  };





} (window.VLAssetMapMarkerData = window.VLAssetMapMarkerData || {}, jQuery));
